minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.250
loader_version_range=[1,)
moddev_version=2.0.146
java_version=21
source_directory=src/1.21.1-neoforge
archive_suffix=-neoforge-1.21.1
target_label=Minecraft 1.21.1 NeoForge
