minecraft_version=1.21.11
minecraft_version_range=[1.21.11]
neoforge_version=21.11.45
loader_version_range=[1,)
moddev_version=2.0.147
java_version=21
source_directory=src/1.21.11-neoforge
archive_suffix=-neoforge-1.21.11
target_label=Minecraft 1.21.11 NeoForge