minecraft_version=1.21.1
loader_version=0.16.14
loom_version=1.17.20
fabric_api_version=0.116.15+1.21.1
modmenu_version=11.0.4
java_version=21
uses_legacy_mod_configurations=true
source_directory=src/1.21.1
excluded_root_java_sources=dev/fpstune/mixin/LevelRendererMixin.java,dev/fpstune/screen/FPSTuneConfigScreen.java,dev/fpstune/screen/FPSTuneAdvancedConfigScreen.java
excluded_root_resources=
archive_suffix=-mc1.21.1
target_label=Minecraft 1.21.1
