minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.20
fabric_api_version=0.158.0+26.2
modmenu_version=20.0.0-beta.4
java_version=25
uses_legacy_mod_configurations=false
source_directory=src/26.2
excluded_root_java_sources=
excluded_root_resources=
archive_suffix=
target_label=Minecraft 26.2
