minecraft_version=26.2
minecraft_version_range=[26.2]
neoforge_version=26.2.0.77
moddev_version=2.0.146
java_version=25
source_directory=src/26.2-neoforge
archive_suffix=-neoforge-26.2
target_label=Minecraft 26.2 NeoForge
