minecraft_version=26.3
minecraft_version_range=[26.3]
neoforge_version=26.3.0.7-beta
moddev_version=2.0.147
java_version=25
source_directory=src/26.3-neoforge
archive_suffix=-neoforge-26.3
target_label=Minecraft 26.3 NeoForge
