minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.20
fabric_api_version=0.160.6+26.3
modmenu_version=21.0.0-beta.1
java_version=25
uses_legacy_mod_configurations=false
source_directory=src/26.3
excluded_root_java_sources=
excluded_root_resources=
archive_suffix=-mc26.3
target_label=Minecraft 26.3
